"""Saving, loading, and reading traces.

A trace is the full record of one request: the question, everything the model
saw (the system prompt and the retrieved chunks), and the answer. Traces are
saved as CSV so you can open them in any spreadsheet.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

import pandas as pd

DATA_DIR = Path(__file__).resolve().parent.parent / "data"

COLUMNS = [
    "Trace ID", "Query Topic", "User Query", "History", "AI Response",
    "Retrieved Chunks", "Prompt Version", "Model", "Source",
]


@dataclass
class Trace:
    trace_id: str
    query_topic: str
    user_query: str
    history: list[dict]
    ai_response: str
    retrieved_ids: list[str] = field(default_factory=list)
    prompt_version: str = ""
    model: str = ""
    source: str = "live"   # "live" = generated by the bot, "curated" = written for the workshop

    def to_row(self) -> dict:
        return {
            "Trace ID": self.trace_id,
            "Query Topic": self.query_topic,
            "User Query": self.user_query,
            "History": format_history(self.history),
            "AI Response": self.ai_response,
            "Retrieved Chunks": json.dumps(self.retrieved_ids),
            "Prompt Version": self.prompt_version,
            "Model": self.model,
            "Source": self.source,
        }


def format_history(messages: list[dict]) -> str:
    """Turn chat messages into plain text that reads well in a spreadsheet cell."""
    return "\n\n".join(f"{m['role'].upper()}:\n{m['content']}" for m in messages)


def save_traces(traces: list[Trace], path: str | Path) -> pd.DataFrame:
    df = pd.DataFrame([t.to_row() for t in traces], columns=COLUMNS)
    df.to_csv(path, index=False)
    return df


def load_traces(path: str | Path) -> pd.DataFrame:
    path = Path(path)
    if not path.is_absolute() and not path.exists():
        path = DATA_DIR / path
    return pd.read_csv(path, keep_default_na=False)


def show_trace(df: pd.DataFrame, i: int, show_history: bool = True) -> None:
    """Print one trace so it's easy to read in a notebook."""
    row = df.iloc[i]
    bar = "=" * 80
    print(bar)
    print(f"Trace {row['Trace ID']}   ({i + 1} of {len(df)})   topic: {row.get('Query Topic', '')}")
    print(bar)
    print(f"USER QUERY:\n{row['User Query']}\n")
    if show_history:
        print("HISTORY (everything the model saw):")
        print(row["History"])
        print()
    print(f"AI RESPONSE:\n{row['AI Response']}")
    print(bar)
